### ISSUE TITLE
Sheet title not included in GenericObject Meta properties

### ISSUE THREAD

**Issue by avb-qlik** [qlik-oss/enigma-go#19]
### Description
I'm trying to get the title of a sheet in QCB local dev environment this way

` sheet, err := doc.GetObject(context, "2496d12e-02bc-47a5-964c-f11989d8152e")`
` l, err := sheet.GetLayout(context)`

but `l.Meta` as not the object I'm expecting, it contains only one `Name` property (which is actually empty). 

In the Qlik Sense Enterprise dev hub the `GetLayout` method gives me this: 
![image](https://user-images.githubusercontent.com/23073135/40668820-c5e0e2aa-6365-11e8-8778-f26ea5701b40.png)

and the title is there.

##### Expected behavior

Expecting to get a `Meta` object that includes the `title` property.

Am I missing something? Any suggestion? Thanks

### Environment
QSB local dev

##### Operating system
```
[ ] Windows
[ ] OSX
[x] Linux
```

**Comment by peol** [comment]
Hi, I believe the problem here is that client-specific properties (i.e. properties in the JSON response _without_ a `q` prefix) needs to be defined in your own custom struct for sheet. The generic object itself does not contain this property. Similar to this example: https://github.com/qlik-oss/enigma-go/blob/master/examples/basics/custom-type/custom-type.go

**Comment by avb-qlik** [comment]
I see but in this case I need to read the property not to write it.

**Comment by gabbaxx** [comment]
Get the layout using the `GetLayoutRaw` function instead to get the full json data:
```
sheet, err := doc.GetObject(ctx, "2496d12e-02bc-47a5-964c-f11989d8152e")
  raw, err := sheet.GetLayoutRaw(ctx)
```
Then unmarshal the raw data into a _custom_ struct that extends the standard enigma structs with the extra fields you need
```
layoutWithTitle := &LayoutWithTitle{}
err = json.Unmarshal(raw, layoutWithTitle)
fmt.Println("Title: ", layoutWithTitle.Meta.Title)
```
The custom struct that adds adds the Title field to Meta can look for instance like this:
```
type LayoutWithTitle struct {
  enigma.GenericObjectLayout
  Meta struct {
    enigma.NxMetaDef
    Title string `json:"title"`
  } `json:"qMeta"`
}
```
Hope that helps!

**Comment by avb-qlik** [comment]
Yes, thanks! :) I've just discovered the `GetLayoutRaw` method :)
Now I can unmarshall everything I need.
