### ISSUE TITLE
all available versions of enimga-go module does not contain v2.0.0 ... v3.0.1.

### ISSUE THREAD

**Issue by ttcodegear** [qlik-oss/enigma-go#219]
$>go list -m -versions github.com/qlik-oss/enigma-go
github.com/qlik-oss/enigma-go v0.1.0 v0.1.1 v1.0.0 v1.1.0 v1.1.1 v1.1.2 v1.2.0

**Comment by ttcodegear** [comment]
and, module 'github.com/qlik-oss/enigma-go/v3' is invalid.
$>go list -m -versions github.com/qlik-oss/enigma-go/v3
go list -m: loading module retractions for github.com/qlik-oss/enigma-go/v3@v3.0.0: version "v3.0.1" invalid: go.mod has non-.../v3 module path "github.com/qlik-oss/enigma-go/v2" (and .../v3/go.mod does not exist) at revision v3.0.1

**Comment by wennmo** [comment]
Thanks @ttcodegear, we will look into this

**Comment by wennmo** [comment]
There was an issue with the tags for the `v3.0.0` and `v3.0.1`, which were pointing to the wrong commits. This should have been resolved now. 

@ttcodegear, is it possible for you to verify that you are no longer seeing the problem? Thanks for reporting the issue 🙇

**Comment by ttcodegear** [comment]
ok, v3.0.1 is available. many thanks.

$>go list -m -versions github.com/qlik-oss/enigma-go/v3
github.com/qlik-oss/enigma-go/v3 v3.0.0 v3.0.1

$>go get -u github.com/qlik-oss/enigma-go/v3
go: downloading github.com/qlik-oss/enigma-go/v3 v3.0.1
go: downloading github.com/qlik-oss/enigma-go v1.2.0
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/pkg/errors v0.9.1
go get: added github.com/qlik-oss/enigma-go/v3 v3.0.1
