### ISSUE TITLE
Create API specification usable for API governance application

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/enigma-go#23]
Investigate how and possibly create way to generate API specification which can be parsed and used by the API Governance application. 

Describe scope, estimated size and design

**Comment by glooms** [comment]
It was suggested by @aihazm that we should try to create an API similar to that of **enigma.js**. I've been searching for some sort of standardized format for go-package/library APIs without much luck.

Given that, I have too suggestions:

1. Use **godoc**. We already use it for enigma-go and it is the standard for documenting packages in go. We might want to filter the generated code but it could also be nice to have under governance as it would give us insights as to how the qix-api changes affect enigma-go.

2. Build a custom solution for generating go-package APIs tailored to API governance, similar too **scriptappy**. This might be a viable approach, albiet more time-consuming. Could be done by using **godoc** and manipulating the output. 


I will investigate both approaches.

**Comment by glooms** [comment]
I don't know how much information we want to include in the API spec but with any **godoc** approach we will have problems handling some constants and variables.

If they are declared as so:
```
const A = 10
var S = "Hello"
```
the information we get from godoc is the same as the source, meaning we have interpret what the type is ourselves. This is a problem under the assumption that we want our specification to reflect the strongly typed nature of go and state the specific types used for constants, variables, arguments e.t.c.

I will see what can be done without using godoc.

**Comment by glooms** [comment]
Working on a general solution using go's compiler resources. This is the way godoc is built too but as we want some information that godoc strips we cannot simply rely on parsing its ouput.

It was suggested that we could make specification in either `yaml` or `json` format, although I'm not there yet I've gotten a part of the way.

I made a temporary repo in which I'm working: https://github.com/glooms/spec

**Comment by glooms** [comment]
Pretty much done with the API specification groundwork.
Using `go/types` we can get basically a typed specification equivalent to what is used internally by **go** so it should be pretty robust. (What works in according to the language reference should work with this solution.)

What remains is to figure how to include comments (probably not too hard but we might need to use the AST (`go/ast`), as I think that the comments are removed at this stage in the compiling process).

There is also a bit left regarding how to actually generate the specification, what format, what information is needed etc. But we have all the information we need to do it (except for the comments).

Checkout the previously mentioned repo.

**Comment by wennmo** [comment]
Closed in #93
