### ISSUE TITLE
Could you please share `schema.json` used for API autogeneration

### ISSUE THREAD

**Issue by vadimtsushko** [qlik-oss/enigma-go#5]
Hi. Thank you for the great project.

I may be completely wrong, knowing nothing about go but I looked into `/schema/generate.go` sources anyway and it looks for me that you have pretty rich schema as an input for your code generation. 
So is `schema.json` you use different from those used in `enigma.js` as https://github.com/qlik-oss/enigma.js/blob/master/schemas/12.67.2.json for example?
If so, could you please make it available to the community - including in this repo or by any other means?
It would be very helpful for those of us who try to use QIX in other statically typed languages (like Dart in my case)

**Comment by peol** [comment]
Hi @vadimtsushko. You're completely right, there is a schema (which isn't the same as in enigma.js). We have plans on opening that up but we don't have an ETA right now (but hopefully soon). I'll let this issue sit until we have a way for the public to access it :)

**Comment by vadimtsushko** [comment]
Thank you for confirmation.
I'm excited for new developments in Qlik and look forward to get this schema :)

**Comment by peol** [comment]
As stated on the Qlik Branch slack, there are _experimental_ APIs in newer version of Qlik Associative Engine to fetch this: `http://engine/jsonrpc-api`. It may change in the future so be careful :)
