### ISSUE TITLE
Opening a second Sense app, quickly after the first, sometimes results in error.

### ISSUE THREAD

**Issue by qlikmats** [qlik-oss/enigma-go#51]
### Description

Opening a second Sense app, quickly after the first, sometimes results in error.

### Steps to Reproduce
Start a local Sense engine, and populate it with two apps (called _app_1_ and _app_2_)
Use engine uri "ws://localhost:9076/"

1. Connect to Sense engine and open app_1
2. Disconnect from Sense engine
3. Connect to Sense engine and open app_2

##### Expected behavior

app_2 opens w/o error

##### Actual behavior

app_2 fails to open, and I get an error like:

<*enigma.qixError | 0xc00026e510>: {
    ErrorCode: 1002,
    ErrorParameter: `"app_2.qvf",`
    ErrorMessage: "App already open",
}

The error occurs **frequently**, but **not always**. Putting a small (~1s) sleep between disconnect and connect reduces the chances of encountering the error. Using a random engine url in each new connect (i.e. Dial("ws://localhost/app/[randomstr]")) seems to cause the problem to **not** occur.

##### Operating system
```
[ ] Windows
[ ] OSX
[X ] Linux
```

### Versions

* Version of Go (go version): 
go1.11.1 linux/amd64

### Example
`global, err := dialer.Dial(ctx, "ws://localhost:9076/", nil)`
`doc, err := global.OpenDoc(ctx, "app_1.qvf", "", "", "", false)`
`global.DisconnectFromServer()`

`//time.Sleep(1 * time.Second)`

`global, err = dialer.Dial(ctx, "ws://localhost:9076/", nil)`
`doc, err = global.OpenDoc(ctx, "app_2.qvf", "", "", "", false)`
`global.DisconnectFromServer()`

**Comment by glooms** [comment]
Hi @qlikmats, a bit overdue but I cannot seem to reproduce the error you got.
I only get the error if I don't disconnect from server in between, which is expected behavior. The difference might be that I am using go1.12.5 linux/amd64 but I have a hunch it might be engine related.

Could you see if you can still replicate this error?
