### ISSUE TITLE
Investigate code coverage of unit and integration tests

### ISSUE THREAD

**Issue by wennmo** [qlik-oss/enigma-go#87]
We need to be able to measure the code coverage of the testing being done in enigma-go. Investigate if e.g. `SonarCube` can be used as a gatekeeper for PRs and in CCI.

**Comment by peol** [comment]
```
docker run -d --name sonarqube -p 9000:9000 sonarqube
brew install sonar-scanner
```

Then set up a project on http://localhost:9000 and go through the guide, copy the `sonar-scanner` command it generated and run it in your local copy of the git repo.
